name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  fl_chart: 1.0.0
  http: ^1.2.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+1
  path: ^1.8.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/math.jpeg
    - assets/images/hanoi.jpg
    - assets/images/mercury.webp
    - assets/images/truyen_kieu.jpeg
    - assets/images/8.png
    - assets/images/worldcup.jpeg
    - assets/images/oxygen.webp
    - assets/images/1945.jpg
    - assets/images/ho_babe.jpeg
    - assets/images/cavoixanh.jpg
    - assets/images/dalat.jpeg
    - assets/images/edison.jpg
    - assets/images/lotus.jpg
    - assets/images/songdongnai.webp
    - assets/images/mars.jpg
    - assets/images/Parasite.jpg
    - assets/images/nitrogen.jpg
    - assets/images/gialong.jpeg
    - assets/images/fanxipang.jpg
    - assets/images/danbau.jpg
    - assets/sounds/correct.mp3
    - assets/sounds/incorrect.mp3
    - assets/sounds/background_music.mp3